name: Build
on:
  push:
    branches:
      - 'master'
      - 'dev'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build UTM
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, x86_64]
        platform: [ios, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Setup Xcode
        shell: bash
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app
      - name: Cache Sysroot
        id: cache-sysroot
        uses: actions/cache@v1
        with:
          path: sysroot-${{ matrix.platform }}-${{ matrix.arch }}
          key: ${{ matrix.platform }}-${{ matrix.arch }}-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
      - name: Setup Path
        shell: bash
        run: |
          echo "/usr/local/opt/gettext/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
      - name: Build Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        run: |
          brew uninstall cmake
          brew install bison pkg-config nasm make meson
          rm -f /usr/local/lib/pkgconfig/*.pc
          ./scripts/build_dependencies.sh -p ${{ matrix.platform }} -a ${{ matrix.arch }}
      - name: Compress Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        run: |
          mkdir sysroot_tar
          tar cf sysroot_tar/sysroot.tgz sysroot*
      - name: Upload Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v1
        with:
          name: Sysroot-${{ matrix.platform }}-${{ matrix.arch }}
          path: sysroot_tar
      - name: Build UTM
        run: ./scripts/build_utm.sh -p ${{ matrix.platform }} -a ${{ matrix.arch }} -o build-utm/UTM
      - name: Upload UTM
        uses: actions/upload-artifact@v1
        with:
          name: UTM-${{ matrix.platform }}-${{ matrix.arch }}
          path: build-utm
  build-universal:
    name: Build UTM (macOS Universal)
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Cache Sysroot
        id: cache-sysroot
        uses: actions/cache@v1
        with:
          path: sysroot-macOS-arm64_x86_64
          key: macos-universal-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
      - name: Download Sysroot (arm64)
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        id: cache-sysroot-arm64
        uses: actions/cache@v1
        with:
          path: sysroot-macOS-arm64
          key: macos-arm64-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
      - name: Download Sysroot (x86_64)
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        id: cache-sysroot-x86_64
        uses: actions/cache@v1
        with:
          path: sysroot-macOS-x86_64
          key: macos-x86_64-${{ hashFiles('scripts/build_dependencies.sh') }}-${{ hashFiles('patches/**') }}
      - name: Check sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true' && (steps.cache-sysroot-arm64.cache-hit != 'true' || steps.cache-sysroot-x86_64.cache-hit != 'true')
        run: |
          echo No cached sysroot found!
          exit 1
      - name: Pack Universal Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        run: ./scripts/pack_dependencies.sh . macos arm64 x86_64
      - name: Compress Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        run: |
          rm -rf sysroot_tar
          mkdir sysroot_tar
          tar cf sysroot_tar/sysroot.tgz sysroot-macOS-arm64_x86_64
      - name: Upload Sysroot
        if: steps.cache-sysroot.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v1
        with:
          name: Sysroot-macos-universal
          path: sysroot_tar
      - name: Setup Xcode
        shell: bash
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app
      - name: Build UTM
        run: ./scripts/build_utm.sh -p macos -a "arm64 x86_64" -o build-utm/UTM
      - name: Upload UTM
        uses: actions/upload-artifact@v1
        with:
          name: UTM-macos-universal
          path: build-utm
  package-ipa:
    name: Package (iOS IPA)
    runs-on: macos-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: UTM-ios-arm64
      - name: Install ldid
        run: brew install ldid
      - name: Fakesign IPA
        run: ./scripts/package.sh ipa UTM-ios-arm64/UTM.xcarchive .
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: UTM.ipa
          asset_name: UTM.ipa
          asset_content_type: application/octet-stream
      - name: Send Dispatch Event
        continue-on-error: true
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ secrets.DISPATCH_ALTSTORE_REPO_NAME }}
          event-type: new-release
  package-deb:
    name: Package (iOS DEB)
    runs-on: macos-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: UTM-ios-arm64
      - name: Install ldid + dpkg
        run: brew install ldid dpkg
      - name: Fakesign IPA
        run: ./scripts/package.sh deb UTM-ios-arm64/UTM.xcarchive .
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: UTM.deb
          asset_name: UTM.deb
          asset_content_type: application/octet-stream
      - name: Send Dispatch Event
        continue-on-error: true
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ secrets.DISPATCH_CYDIA_REPO_NAME }}
          event-type: new-release
  package-mac:
    name: Package (macOS)
    runs-on: macos-latest
    needs: build-universal
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Import signing certificate into keychain
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: UTM-macos-universal
      - name: Fixup Permissions
        run: find UTM-macos-universal/UTM.xcarchive -type f \( -path '*/Contents/MacOS/*' -or -path '*/Frameworks/*.dylib' \) -exec chmod +x \{\} \;
      - name: Package for Release
        run: ./scripts/package_mac.sh UTM-macos-universal/UTM.xcarchive . "$SIGNING_TEAM_ID"
        env:
          SIGNING_TEAM_ID: ${{ secrets.SIGNING_TEAM_ID }}
      - name: Notarize app
        run: npx notarize-cli --file "UTM.dmg" --bundle-id "com.utmapp.UTM"
        env:
          NOTARIZE_USERNAME: ${{ secrets.SIGNING_USERNAME }}
          NOTARIZE_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: UTM.dmg
          asset_name: UTM.dmg
          asset_content_type: application/octet-stream
